config/routes.rb
Rails.application.routes.draw do





  get 'search', to: 'search#results'

  devise_for :users, controllers: { registrations: "registrations" }
  resources :users, :only => [:index, :show, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :companies do
    resources :activities
  end

  resources :conversations do
    resources :messages
 end

  root to: "home#index"

  get 'page/about'
  get 'page/contact'

  get 'admin/index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  #this class manages who can do what and sets up roles and abilities
  def initialize(user)

    user ||= User.new # guest user (not logged in)
    can :read, :all
    if user.nil?
      # guest user
    elsif user.admin?
      can :manage, :all
    else
      can :create, [Company,Activity,Conversation,Message]
      can :manage, User,  :user_id => user.id
      can :manage, Conversation,  :user_id => user.id
      can [:manage], Company do |company|
           company.try(:user) == user
       end
       can [:manage], Activity do |activity|
            activity.company.try(:user) == user
       end
  end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/activity.rb
class Activity < ApplicationRecord

    #relationship
  	belongs_to :company

    #converting address to lat and long
    geocoded_by :location
    after_validation :geocode
    after_validation :geocode, if: ->(obj){ obj.location.present? and obj.location_changed? }

    #takes care of image upload
    mount_uploader :image, ImageUploader

    #attribute vaildations
    validates :activity_name, presence: true
    validates :description, presence: true
    validates :start_date, presence: true
    validates :end_date, presence: true
    validates :location, presence: true
    validates :mobile, numericality: { only_integer: true}, :allow_blank => true
    validates :telephone, numericality: { only_integer: true}, :allow_blank => true

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord

  has_many :activities, dependent: :destroy
	belongs_to :user

  geocoded_by :location
  after_validation :geocode

  after_validation :geocode, if: ->(obj){ obj.location.present? and obj.location_changed? }

  mount_uploader :image, ImageUploader

  validates :company_name, presence: true
  validates :description, presence: true
  validates :location, presence: true

end

app/models/conversation.rb
class Conversation < ApplicationRecord
  validates :user_id, :subject, :receiver_id, presence: true
  has_many :user_conversations, dependent: :destroy
  has_many :users, through: :user_conversations
  has_many :messages, dependent: :destroy
  belongs_to :user

  after_create :add_user_to_conversation

  private

  def add_user_to_conversation
    UserConversation.create(user_id: receiver_id, conversation: self)
    UserConversation.create(user: self.user, conversation: self)
  end

end

app/models/message.rb
class Message < ApplicationRecord


  validates :message, :conversation_id, :user_id, presence: true

  belongs_to :conversation
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :companies, dependent: :destroy
  has_many :user_conversations, dependent: :destroy
  has_many :conversations, through: :user_conversations, dependent: :destroy

  geocoded_by :current_location
  after_validation :geocode

  after_validation :geocode, if: ->(obj){ obj.current_location.present? and obj.current_location_changed? }

  mount_uploader :image, ImageUploader

  enum gender: [ :male, :female ]

  validates :first_name, :last_name, presence: true, format: { with: /\A[a-zA-Z]+\z/, message: "Only allows letters" }

end

app/models/user_conversation.rb
class UserConversation < ApplicationRecord
  belongs_to :user
  belongs_to :conversation
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  #before any action in this controller check if they are an admin
  before_filter :check_if_admin

  def index
  end

  protected
  def check_if_admin
    #checks if the person is an admin, if not redirects back to root_url
    if !current_user.admin?
      flash[:alert] = 'Only Admins allowed!'
      redirect_to root_url
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  # before_action :authenticate_user!

  def index

    #requests ip address and finds city
    @location = Geocoder.search(request.remote_ip).first.city # => "Cork"

    #finds companies in the city within 50km
    #query is limited to 4 companies, if there is a more a variable is set to true (for view use).
    @noofcompanies = Company.near(@location, 50).size
    if @noofcompanies > 4
      @lotsofcompanies = true
    else
      @lotsofcompanies = false
    end
    @companies = Company.near(@location, 50).limit(4)

    #finds activities in the city within 50km
    #query is limited to 4 activities, if there is a more a variable is set to true (for view use).
    @noofactivities = Activity.near(@location, 50).size
    if @noofactivities > 4
      @lotsofactivities = true
    else
      @lotsofactivities = false
    end
    @activities = Activity.near(@location, 50).limit(4)

    #find all users who are ready to work
    #query is limited to 4 users, if there is a more a variable is set to true (for view use).
    @users = User.where(available_for_work: true)
    @noofusers = @users.near(@location, 50).size
    if @noofusers > 4
      @lotsofusers = true
    else
      @lotsofusers = false
    end
    @users = @users.near(@location, 50).limit(4)

  end

end

app/controllers/page_controller.rb
class PageController < ApplicationController

  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!
  before_filter :check_if_admin, only: [:index, :destroy]


  def index
     @users = User.all
  end

  def show
    @user = User.find(params[:id])
    today = Date.today
    d = Date.new(today.year, @user.date_of_birth.month, @user.date_of_birth.day)
    @age = d.year - @user.date_of_birth.year - (d > today ? 1 : 0)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  protected

  def check_if_admin
    if !current_user.admin?
      flash[:alert] = 'Only Admins allowed!'
      redirect_to root_url
    end
  end


end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="container">
  <h2 style="text-align:center"><strong id="brand">BrandSpace</strong> We believe in a community,
  built by all of us.</h2>
  <br/>
</div>

<div id="coverimg"></div>

<div class="container">

  <br/>
  <% if !@activities.nil? %>
    <h3>Activities around <%= @location%></h3>
    <div class="row">
      <div class="card-deck">
        <% @activities.each do |activity| %>
          <div class="card text-center" style="width: 17rem;">
            <% if activity.image? %>
            <%= image_tag activity.image_url(:med), class:"card-img-top" %>
            <% end %>
            <div class="card-block">
              <h4 class="card-title">
                <%= activity.activity_name %>
              </h4>
              <p class="card-text">
                <%= activity.location %>
              </p>
            </div>
            <div class="card-footer">
              <%= link_to "Go to Activity", company_activity_path(activity.company_id, activity.id), class:"btn btn-outline-primary" %>
            </div>
          </div>
        <%end%>
      </div>
    </div>
    <br/>
    <% if @lotsofactivities == true %>
    <%= link_to 'More Activities', search_path(:q => @location, :category => "alocation"), class:"btn btn-outline-info" %>
    <%end%>
    <br/>
  <%end%>

  <br/>

  <% if !@companies.nil? %>
    <h3>Companies around <%= @location%></h3>
    <div class="row">
      <div class="card-deck">
        <% @companies.each do |company| %>
          <div class="card text-center" style="width: 17rem;">
            <% if company.image? %>
            <%= image_tag company.image_url(:med), class:"card-img-top" %>
            <% end %>
            <div class="card-block">
              <h4 class="card-title">
                <%= company.company_name %>
              </h4>
              <p class="card-text">
                <%= company.location %>
              </p>
            </div>
            <div class="card-footer">
              <%= link_to "Go to Company", company_path(company.id), class:"btn btn-outline-primary" %>
            </div>
        </div>
        <%end%>
      </div>
    </div>
    <br/>
    <% if @lotsofcompanies == true %>
    <%= link_to 'More Companies', search_path(:q => @location, :category => "clocation"), class:"btn btn-outline-info" %>
    <%end%>
    <br/>
  <%end%>

  <br/>

  <% if !@users.nil? %>
  <br/>
    <h3>Users around <%= @location%></h3>
    <div class="row">
      <div class="card-deck">
        <% @users.each do |user| %>
          <div class="card text-center" style="width: 17rem;">
            <% if user.image? %>
            <%= image_tag user.image_url(:med), class:"card-img-top" %>
            <% end %>
            <div class="card-block">
              <h4 class="card-title">
                <%= user.first_name %> <%= user.last_name %>
              </h4>
              <p class="card-text">
                <%= user.current_location %>
              </p>
            </div>
            <div class="card-footer">
              <%= link_to "Go to User", user_path(user.id), class:"btn btn-outline-primary" %>
            </div>
        </div>
        <%end%>
      </div>
    </div>
    <br/>
    <% if @lotsofusers == true %>
    <%= link_to 'More Users', search_path(:q => @location, :category => "ulocation"), class:"btn btn-outline-info" %>
    <%end%>
    <br/>
  <%end%>

</div>