config/routes.rb
Rails.application.routes.draw do





  get 'search', to: 'search#results'

  devise_for :users, controllers: { registrations: "registrations" }
  resources :users, :only => [:index, :show, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :companies do
    resources :activities
  end

  resources :conversations do
    resources :messages
 end

  root to: "home#index"

  get 'page/about'
  get 'page/contact'

  get 'admin/index'

end

app/models/company.rb
class Company < ApplicationRecord

  has_many :activities, dependent: :destroy
	belongs_to :user

  geocoded_by :location
  after_validation :geocode

  after_validation :geocode, if: ->(obj){ obj.location.present? and obj.location_changed? }

  mount_uploader :image, ImageUploader

  validates :company_name, presence: true
  validates :description, presence: true
  validates :location, presence: true

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  #make sure the user is logged in for every action, except show
  before_action :authenticate_user!, except: [:show]
  load_and_authorize_resource

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    #the company with the id passed in, is retrieved
		@company = Company.find(params[:id])
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
    @company = Company.find(params[:id])
  end

  # POST /companies
  # POST /companies.json
  def create
    #the new company's parameters are received from the form and stored
		@company = current_user.companies.build(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    @company = Company.find(params[:id])

    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company = Company.find(params[:id])
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_company
    #   @company = Company.find(params[:id])
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:company_name, :description, :location, :image)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
  <%= form_for(company, html: { multipart: :true}) do |f| %>
    <% if company.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

        <ul>
        <% company.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <div class="input-group mb-2 mr-sm-2 mb-sm-0">
        <div class="input-group-addon"><i class="fa fa-building-o" aria-hidden="true"></i></div>
        <%= f.text_field :company_name, class:"form-control", placeholder:"Organisation Name", autofocus: true %>
      </div>
    </div>

    <div class="form-group">
      <div class="input-group mb-2 mr-sm-2 mb-sm-0">
        <div class="input-group-addon"><i class="fa fa-file-text" aria-hidden="true"></i></div>
        <%= f.text_area :description, class:"form-control", placeholder:"Organisation Description", rows:"10" %>
      </div>
    </div>

  <div class="form-group">
    <i class="fa fa-picture-o" aria-hidden="true"></i>  <%= f.label :image %> -  
    <%= f.file_field :image %>
  </div>

    <div class="form-group">
      <div class="input-group mb-2 mr-sm-2 mb-sm-0">
        <div class="input-group-addon"><i class="fa fa-map-marker" aria-hidden="true"></i></div>
        <%= f.text_field :location, class:"form-control", placeholder:"Company Location" %>
      </div>
    </div>

    <div class="actions">
      <%= f.submit class:"btn btn-success btn-block" %>
    </div>
  <% end %>

app/views/companies/edit.html.erb
<div class="container">

  <div class="card">
    <h3 class="card-header">Edit Organisation</h3>

    <div style="padding:20px">

      <%= render 'form', company: @company %>

    </div>

    <div class="card-footer">
      <%= link_to 'Show', @company , class:"btn btn-outline-primary btn-block" %>
      <br/>
      <br/>
      <%= link_to 'Back', companies_path, class:"btn btn-secondary btn-block" %>
    </div>

  </div>

</div>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">

  <% if can? :create, Company %>
  <%= link_to 'New Company', new_company_path, class:"btn btn-outline-success" %>
  <%end%>
  <br/>
  <br/>

  <h1>Your Organisation(s)</h1>
  <br/>

  <div class="row">
    <div class="card-deck">
      <% current_user.companies.each do |company| %>
      <div class="card text-center" style="width: 17rem;">
        <%= image_tag company.image_url(:med), class:"card-img-top" %>
        <div class="card-block">
          <h4 class="card-title"><%= company.company_name%></h4>
          <p class="card-text"><%= company.location%></p>
        </div>
        <div class="card-footer">
          <%= link_to 'Go to Company', company, class: "btn btn-outline-primary" %>
        </div>
      </div>
      <% end %>
    </div>
  </div>

  <% if current_user.admin? %>
  <br/>
  <h1>All Organisations</h1>
  <br/>

  <div class="row">
    <div class="card-deck">
    <% @companies.each do |company| %>
      <div class="card text-center" style="width: 17rem;">
        <% if company.image? %>
        <%= image_tag company.image_url(:med), class:"card-img-top" %>
        <% end %>
        <div class="card-block">
          <h4 class="card-title">
            <%= company.company_name %>
          </h4>
          <p class="card-text">
            <%= company.location %>
          </p>
        </div>
        <div class="card-footer">
          <%= link_to "Go to Company", company_path(company.id), class:"btn btn-outline-primary" %>
        </div>
      </div>
      <%end%>
    </div>
  </div>
  <%end%>

</div>

app/views/companies/new.html.erb
<div class="container">

  <div class="card">
    <h3 class="card-header">New Organisation</h3>

    <div style="padding:20px">

    <%= render 'form', company: @company %>

    </div>

    <div class="card-footer">
      <%= link_to 'Back', companies_path, class:"btn btn-secondary btn-block" %>
    </div>

  </div>

</div>

app/views/companies/show.html.erb
<div class="container">

  <div class="card-group">
    <div class="card">
      <div class="card-block">
        <% if @company.image? %>
        <%= image_tag @company.image_url(:lrg), class:"card-img-top", style:"height:500px, width:100%" %>
        <% end %>
        <div class="card-block">
          <h4 class="card-title"><%= @company.company_name %></h4>
          <p class="card-text"><strong>Description: </strong><%= @company.description%></p>
          <% if  current_user.admin? %>
          <%= link_to 'Owner Profile', user_path(@company.user_id), class: "btn btn-outline-warning" %>
          |
          <% end %>
          <% if can? :update, @company %>
          <%= link_to 'Edit', edit_company_path(@company), class: "btn btn-outline-primary" %>
          |
          <% end %>
          <% if can? :destroy, @company %>
          <%= link_to 'Delete', company_path(@company), data: { confirm: "Are you sure?" }, method: :delete, class:"btn btn-outline-danger" %>
          |
          <% end %>
          <br/>
          <br/>
          <h4>All related Activites:</h4>
          <div class="list-group">
            <% if can? :manage, @company %>
            <a href="/companies/<%= @company.id %>/activities/new" class="list-group-item list-group-item-action list-group-item-success">
              Create New Activity
            </a>
            <% end %>
            <% @company.activities.each do |activity| %>
            <a href="/companies/<%= @company.id %>/activities/<%= activity.id %>" class="list-group-item list-group-item-action"><%= activity.activity_name%></a>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <% if @company.location? %>
  <div class="card-group">
    <div class="card text-center">
      <div class="card-block">
        <div id="mapouter">
          <div id="gmap_canvas">
            <iframe width="1060" height="500" frameborder="0" scrolling="no" marginheight="0" src="https://maps.google.com/maps?q=<%= @company.location %>, IE, &t=&z=17&ie=UTF8&iwloc=&output=embed" marginwidth="0"></iframe>
          </div>
          <style>#gmap_canvas{height:500px;width:1060px;}#mapouter{overflow:hidden;height:500px;width:1060px;}</style>
        </div>
      </div>
    </div>
  </div>
  <%end%>

</div>