config/routes.rb
Rails.application.routes.draw do





  get 'search', to: 'search#results'

  devise_for :users, controllers: { registrations: "registrations" }
  resources :users, :only => [:index, :show, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :companies do
    resources :activities
  end

  resources :conversations do
    resources :messages
 end

  root to: "home#index"

  get 'page/about'
  get 'page/contact'

  get 'admin/index'

end

app/models/activity.rb
class Activity < ApplicationRecord

    #relationship
  	belongs_to :company

    #converting address to lat and long
    geocoded_by :location
    after_validation :geocode
    after_validation :geocode, if: ->(obj){ obj.location.present? and obj.location_changed? }

    #takes care of image upload
    mount_uploader :image, ImageUploader

    #attribute vaildations
    validates :activity_name, presence: true
    validates :description, presence: true
    validates :start_date, presence: true
    validates :end_date, presence: true
    validates :location, presence: true
    validates :mobile, numericality: { only_integer: true}, :allow_blank => true
    validates :telephone, numericality: { only_integer: true}, :allow_blank => true

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

  #before doing any action we will see if the user is logged in
  before_action :authenticate_user!
  #finds the related company
  before_action :set_company
  #sets up cancancan abilities
  load_and_authorize_resource

  # GET /activities
  # GET /activities.json
  def index
    # redirects to company page, because it already lists all the associated activities
    redirect_to @company
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
    #finds the activity with the id
    @activity = @company.activities.find(params[:id])
    #finds the associated user
    @user = User.find(@company.user_id)
  end

  # GET /activities/new
  def new
    @activity = @company.activities.new
  end

  # GET /activities/1/edit
  def edit
    @activity =  @company.activities.find(params[:id])
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity =  @company.activities.build(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to company_activity_path @company, @activity, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    @activity =  @company.activities.find(params[:id])

    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to company_activity_path @company, @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity = @company.activities.find(params[:id])

    @activity.destroy
    respond_to do |format|
      format.html { redirect_to company_activities_path @company, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
			@company = Company.find(params[:company_id])
		end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      #these parametes are required before it can be saved.
      params.require(:activity).permit(:activity_name, :description, :start_date, :end_date, :location, :vehicle, :mobile, :telephone, :image)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.erb
<%= form_for([@company, @activity], html: {multipart: :true}) do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">

  <div class="form-group">
    <div class="input-group mb-2 mr-sm-2 mb-sm-0">
      <div class="input-group-addon"><i class="fa fa-users" aria-hidden="true"></i></div>
      <%= f.text_field :activity_name, class:"form-control", placeholder:"Activity Name", autofocus: true %>
    </div>
  </div>

  <div class="form-group">
    <div class="input-group mb-2 mr-sm-2 mb-sm-0">
      <div class="input-group-addon"><i class="fa fa-file-text" aria-hidden="true"></i></div>
      <%= f.text_area :description, class:"form-control", placeholder:"Activity Description", rows:"10" %>
    </div>
  </div>

  <div class="field">
    <%= f.label :start_date %>
    <br/>
    <div class="input-group mb-2 mr-sm-2 mb-sm-0">
      <div class="input-group-addon"><i class="fa fa-calendar" aria-hidden="true"></i></div>
      <%= f.date_select :start_date, class:"form-control", default: Date.today, start_year: Date.today.year %>
    </div>
  </div>

  <div class="field">
    <%= f.label :end_date %>
    <br/>
    <div class="input-group mb-2 mr-sm-2 mb-sm-0">
      <div class="input-group-addon"><i class="fa fa-calendar" aria-hidden="true"></i></div>
      <%= f.date_select :end_date, class:"form-control", default: Date.today, start_year: Date.today.year %>
    </div>
  </div>

  <br/>
  <div class="form-group">
    <i class="fa fa-picture-o" aria-hidden="true"></i>  <%= f.label :image %> -
    <%= f.file_field :image %>
  </div>
  <br/>
  
  <div class="form-group">
    <div class="input-group mb-2 mr-sm-2 mb-sm-0">
      <div class="input-group-addon"><i class="fa fa-map-marker" aria-hidden="true"></i></div>
      <%= f.text_field :location, class:"form-control", placeholder:"Activity Location" %>
    </div>
  </div>


  <div class="form-group">
    <label class="custom-control custom-checkbox">
      <span class="custom-control-description"><i class="fa fa-car" aria-hidden="true"></i> <%= f.label :vehicle %></span>
      <%= f.check_box :vehicle, class:"custom-control-input" %>
      <span class="custom-control-indicator"></span>
    </label>
  </div>

  <div class="form-group">
    <div class="input-group mb-2 mr-sm-2 mb-sm-0">
      <div class="input-group-addon"><i class="fa fa-mobile" aria-hidden="true"></i></div>
      <%= f.text_field :mobile, class:"form-control", placeholder:"Mobile Number" %>
    </div>
  </div>

  <div class="form-group">
    <div class="input-group mb-2 mr-sm-2 mb-sm-0">
      <div class="input-group-addon"><i class="fa fa-phone" aria-hidden="true"></i></div>
      <%= f.text_field :telephone, class:"form-control", placeholder:"Telephone Number" %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit  class:"btn btn-success btn-block"%>
  </div>

<% end %>

 </div>

app/views/activities/edit.html.erb
<div class="container">

  <div class="card">
    <h3 class="card-header">Edit Activity</h3>

    <div style="padding:20px">
      <%= render 'form', activity: @activity %>
    </div>

    <div class="card-footer">
      <%= link_to 'Show', company_activity_path(@company, @activity), class:"btn btn-outline-primary btn-block" %>
      <br/>
      <br/>
      <%= link_to 'Back', company_activity_path(@company), class:"btn btn-secondary btn-block" %>
    </div>

  </div>

</div>

app/views/activities/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">

  <% if current_user.admin? %>
  <br/>
  <h1>All Activities</h1>
  <br/>

  <div class="row">
    <div class="card-deck">
    <% @activities.each do |activity| %>
      <div class="card text-center" style="width: 17rem;">
        <% if activity.image? %>
        <%= image_tag activity.image_url(:med), class:"card-img-top" %>
        <% end %>
        <div class="card-block">
          <h4 class="card-title">
            <%= activity.activity_name %>
          </h4>
          <p class="card-text">
            <%= activity.location %>
          </p>
        </div>
        <div class="card-footer">
          <%= link_to "Go to Activity", company_activity_path(activity.company.id, activity.id), class:"btn btn-outline-primary" %>
        </div>
      </div>
      <%end%>
    </div>
  </div>
  <%end%>

</div>

app/views/activities/new.html.erb
<h1>New Activity</h1>

<%= render 'form' %>

<div class="container">
<%= link_to 'Back', company_activities_path(@company), class:"btn btn-secondary btn-block" %>
</div>

app/views/activities/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <div class="card-group">
    <div class="card">
      <div class="card-block">
        <% if @activity.image? %>
        <%= image_tag @activity.image_url(:lrg), class:"card-img-top", style:"height:500px, width:100%" %>
        <% end %>
        <div class="card-block">
          <h4 class="card-title"><%= @activity.activity_name %></h4>
          <p class="card-text"><strong>Start Date: </strong><%= @activity.start_date.strftime("%d/%m/%Y")%></p>
          <p class="card-text"><strong>End Date: </strong><%= @activity.end_date.strftime("%d/%m/%Y")%></p>
          <p class="card-text"><strong>Description: </strong><%= @activity.description%></p>
          <% if @user.id == current_user.id %>
          <%= link_to 'Find Help Nearby', search_path(:q => @activity.location, :category => "ulocation"), class:"btn btn-outline-warning" %>
          <%end%>
          <br/>
          <br/>
          <% unless @user.id == current_user.id %>
          <%= link_to 'Message Owner', new_conversation_path(:receiver_id => @user.id), class:"btn btn-outline-success" %>
          |
          <%= link_to 'Company Profile', company_path(@activity.company_id), class: "btn btn-outline-warning" %>
          <%end%>
          <% if can? :update, @activity %>
          <%= link_to 'Edit', edit_company_activity_path(@company, @activity), class: "btn btn-outline-primary" %>
          |
          <% end %>
          <% if can? :destroy, @activity %>
          <%= link_to "Delete", company_activity_path(@company, @activity), data: { confirm: "Are you sure?" }, method: :delete, class:"btn btn-outline-danger" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="card-group">
    <% if @activity.vehicle? %>
      <div class="card text-center">
        <div class="card-block">
          <h4 class="card-title">Vehicle: <i class="fa fa-car fa-lg" aria-hidden="true"></i></h4>
        </div>
      </div>
    <%end%>
    <% if @activity.mobile? %>
      <div class="card text-center">
        <div class="card-block">
          <h4 class="card-title"><i class="fa fa-mobile fa-lg" aria-hidden="true"></i> <%= @activity.mobile%></h4>
        </div>
      </div>
    <%end%>
    <% if @activity.telephone? %>
      <div class="card text-center">
        <div class="card-block">
          <h4 class="card-title"><i class="fa fa-phone fa-lg" aria-hidden="true"></i> <%= @activity.telephone%></h4>
        </div>
      </div>
    <%end%>
  </div>

  <% if @activity.location? %>
  <div class="card-group">
    <div class="card text-center">
      <div class="card-block">
        <div id="mapouter">
          <div id="gmap_canvas">
            <iframe width="1060" height="500" frameborder="0" scrolling="no" marginheight="0" src="https://maps.google.com/maps?q=<%= @activity.location %>, IE, &t=&z=17&ie=UTF8&iwloc=&output=embed" marginwidth="0"></iframe>
          </div>
          <style>#gmap_canvas{height:500px;width:1060px;}#mapouter{overflow:hidden;height:500px;width:1060px;}</style>
        </div>
      </div>
    </div>
  </div>
  <%end%>



    <!-- <div class="col-8">
      <strong>Description:</strong> <%= @activity.description %>
      <br/>
      <br/>
      <strong>Start Date:</strong> <%= @activity.start_date %>
      <br/>
      <br/>
      <strong>End Date:</strong> <%= @activity.end_date %>
      <br/>
      <br/>
      <% if @activity.location? %>
      <strong>Address:</strong> <%= @activity.location %>
      (Latitude: <%= @activity.latitude %> Longitude: <%= @activity.longitude%>)
      <br/>
      <div id="mapouter">
        <div id="gmap_canvas">
          <iframe width="600" height="500" frameborder="0" scrolling="no" marginheight="0" src="https://maps.google.com/maps?q=<%= @activity.location %>, IE, &t=&z=17&ie=UTF8&iwloc=&output=embed" marginwidth="0"></iframe>
          <a class="addmaps"href="http://www.map-embed.com/wordpress-themes/"id="get-map-data">Cork, IE, </a>
        </div>
        <style>#gmap_canvas{height:500px;width:600px;}#mapouter{overflow:hidden;height:500px;width:600px;}</style>
      </div>
      <%end%>
      <br/>
      <% if can? :update, @activity %>
      <%= link_to 'Edit', edit_company_activity_path(@company, @activity), class: "btn btn-outline-primary" %>
      |
      <% end %>
      <% if can? :destroy, @activity %>
      <%= link_to "Delete", company_activity_path(@company, @activity), data: { confirm: "Are you sure?" }, method: :delete, class:"btn btn-outline-danger" %>
      |
      <% end %>
      <%= link_to 'Back', company_activities_path(@company), class: "btn btn-secondary" %>
      <br/>
      <br/>

    </div>
  </div> -->

</div>